wf

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -3,7 +3,7 @@ name: Deploy Laravel Application to Production Server v2
 on:
   # Triggers the workflow on push or pull request events but only for the main branch
   push:
-    branches: [ testtest ]
+    branches: [ main ]
 
   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
@@ -36,15 +36,20 @@ jobs:
       run: npm run build
 
     - name: Flushing remote folder except .env and storage
-      continue-on-error: false
+      continue-on-error: true
       uses: appleboy/ssh-action@v0.1.6
       with:
         host: ${{ vars.SSH_HOST }}
         username: ${{ vars.SSH_USER }}
         key: ${{ secrets.SSH_PRIVATE_KEY }}
         script: |
-          cd ${{ vars.SSH_PATH }} && find . -mindepth 1 ! -path './storage/*' ! -name '.env' ! -name 'storage' -exec rm -rf {} +
-
+          if [ -d "${{ vars.SSH_PATH }}" ]; then
+            cd ${{ vars.SSH_PATH }}
+            find . -mindepth 1 ! -path './storage/*' ! -name '.env' ! -name 'storage' -exec rm -rf {} +
+          else
+            echo "Error: Directory ${{ vars.SSH_PATH }} does not exist!" >&2
+            exit 1
+          fi
 
     - name: Synchronize Files To Server
       uses: easingthemes/ssh-deploy@v2.1.5
